// Copyright Samuel Reitich. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

// Shorthand aliases for long gameplay tags that are typed out frequently.
#define FIRST_PERSON CrashGameplayTags::TAG_State_Perspective_FirstPerson
#define THIRD_PERSON CrashGameplayTags::TAG_State_Perspective_ThirdPerson

#define STATE_WAITING_FOR_DATA CrashGameplayTags::TAG_InitState_WaitingForData
#define STATE_INITIALIZING CrashGameplayTags::TAG_InitState_Initializing
#define STATE_GAMEPLAY_READY CrashGameplayTags::TAG_InitState_GameplayReady

/**
 * Defines the native gameplay tags that need to be exposed to C++. All tags that are exposed to C++ should be defined
 * here.
 */
namespace CrashGameplayTags
{
	// Abilities
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_SurvivesDeath);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_InputBlocking);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_Disabled);

	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Slotted_Equipment);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Slotted_Generic);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Slotted_Weapon);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Slotted_Ultimate);

	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Frontend_PrimaryWeapon);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Frontend_SecondaryWeapon);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Frontend_StandardAbility);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Frontend_Passive);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Behavior_UI_Frontend_Ultimate);

	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Identifier_Generic_Jump);


	// Effects
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effects_CameraType_FirstPerson);


	// Gameplay effects
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffects_Damage_CanDamageSelf);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffects_Damage_CanDamageTeam);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffects_Damage_FellOutOfWorld);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffects_Damage_SelfDestruct);


	// Gameplay events
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Ability_Death);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Ability_MeleeSurfaceImpact);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Ability_PerformTargeting);


	// Game framework.
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InitState_WaitingForData);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InitState_Initializing);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InitState_GameplayReady);


	// Input
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Jump);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Look_Mouse);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Look_Stick);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Move);

	// Messages.
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Damage);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Death);

	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Ability_Activated);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Ability_Cooldown_Started);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Ability_Ended);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Ability_Failed);
	
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_Inventory_Change);


	// States
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_AbilityInputBlocked);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Dead);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Dying);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_ImmuneToDamage);


	// UI
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Game);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_GameMenu);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Menu);
	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);

	PROJECTCRASH_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Escape);
};

